version: '3'

services:
  db_alpha:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: alpha
      MYSQL_USER: alpha
      MYSQL_PASSWORD: password_alpha

    volumes:
      - db_alpha_data:/var/lib/mysql
      - ./db_alpha_init.sql:/docker-entrypoint-initdb.d/db_alpha_init.sql
    networks:
      internal_network:
        ipv4_address: 172.30.0.2
    ports:
      - "3307:3306"


  db_beta:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: beta
      MYSQL_USER: beta
      MYSQL_PASSWORD: password_beta
    volumes:
      - db_beta_data:/var/lib/mysql
      - ./db_beta_init.sql:/docker-entrypoint-initdb.d/db_beta_init.sql
    networks:
      internal_network:
        ipv4_address: 172.30.0.3
    ports:
      - "3308:3306"

  

  nextcloud:
    build:
      context: .
      dockerfile: dockerfile_nextcloud
    restart: always
    depends_on:
      - db_alpha
      - db_beta
    ports:
      - "8080:80"
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: password_admin
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
      MYSQL_DATABASE_ALPHA: alpha
      MYSQL_USER_ALPHA: alpha
      MYSQL_PASSWORD_ALPHA: password_alpha
      MYSQL_HOST_ALPHA: db_alpha:3307
      MYSQL_DATABASE_BETA: beta
      MYSQL_USER_BETA: beta
      MYSQL_PASSWORD_BETA: password_beta
      MYSQL_HOST_BETA: db_beta:3308
    volumes:
      - nextcloud_data:/var/www/html


  wordpress:
    build:
      context: .
      dockerfile: dockerfile_wordpress
    restart: always
    depends_on:
      - db_alpha
      - db_beta
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_NAME_ALPHA: alpha
      WORDPRESS_DB_USER_ALPHA: alpha
      WORDPRESS_DB_PASSWORD_ALPHA: password_alpha
      WORDPRESS_DB_HOST_ALPHA: db_alpha:3307
      WORDPRESS_DB_NAME_BETA: beta
      WORDPRESS_DB_USER_BETA: beta
      WORDPRESS_DB_PASSWORD_BETA: password_beta
      WORDPRESS_DB_HOST_BETA: db_beta:3308
    volumes:
      - wordpress_data:/var/www/html


volumes:
  db_alpha_data:
  db_beta_data:
  nextcloud_data:
  wordpress_data:

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24



