version: '3'

services:
  db_alpha:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: alpha
      MYSQL_USER: alpha
      MYSQL_PASSWORD: password_alpha

    volumes:
      - db_alpha_data:/var/lib/mysql
      - ./db_alpha_init.sql:/docker-entrypoint-initdb.d/db_alpha_init.sql
    networks:
      internal_network:
        ipv4_address: 172.30.0.2
    ports:
      - "3306:3306"


  db_beta:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: beta
      MYSQL_USER: beta
      MYSQL_PASSWORD: password_beta
    volumes:
      - db_beta_data:/var/lib/mysql
      - ./db_beta_init.sql:/docker-entrypoint-initdb.d/db_beta_init.sql
    networks:
      internal_network:
        ipv4_address: 172.30.0.3
    ports:
      - "3307:3306"

  

  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - db_alpha
      - db_beta
    ports:
      - "8080:80"
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: password_admin
      MYSQL_DATABASE: alpha,beta
      MYSQL_USER: alpha, beta
      MYSQL_PASSWORD: password_alpha, password_beta
      MYSQL_HOST: db_alpha:3306,db_beta:3307
    volumes:
      - nextcloud_data:/var/www/html


  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db_alpha
      - db_beta
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_NAME: alpha,beta
      WORDPRESS_DB_USER: alpha, beta
      WORDPRESS_DB_PASSWORD: password_alpha, password_beta
      WORDPRESS_DB_HOST: db_alpha:3306,db_beta:3307
    volumes:
      - wordpress_data:/var/www/html


volumes:
  db_alpha_data:
  db_beta_data:
  nextcloud_data:
  wordpress_data:

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24



