- name: Project_playbook
  hosts: servers
  become: false
  any_errors_fatal: true
  vars_files:
    - "{{ playbook_dir }}/vars/vars_app.yaml"
  tasks:
    - name: set nameservers
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"

    - name: update apt
      become: true
      ansible.builtin.apt:
        update_cache: true


    - name: Vérifier si Docker est déjà installé
      stat:
        path: /usr/bin/docker
      register: docker_installed

    - name: Installation de Docker
      become: true
      apt:
        name: docker.io
        state: latest
      when: not docker_installed.stat.exists

    - name: Vérifier si Docker Compose est déjà installé
      stat:
        path: /usr/bin/docker-compose
      register: docker_compose_installed

    - name: Installation de Docker Compose
      become: true
      apt:
        name: docker-compose
        state: latest
      when: not docker_compose_installed.stat.exists

    #GIT PART
    - name: Vérifier si Git est déjà installé
      stat:
        path: /usr/bin/git
      register: git_installed

    - name: Installation de Git
      become: true
      apt:
        name: git
        state: latest
      when: not git_installed.stat.exists

    - name: Clone git repository #Pull si le dossier existe
      become: true
      git:
        repo: https://github.com/Noeeeeeee/projet_devops.git
        update: yes
        dest: /home/project
        version: main

    - name: Install MariaDB Packages
      become: true
      apt:
        name:
          - mariadb-client
          - mariadb-common
          - mariadb-server
        state: present
        update_cache: yes

    - name: Vérifier si GnuPG est déjà installé
      stat:
        path: /usr/bin/gpg
      register: gnupg_installed

    - name: Installation de GnuPG
      become: true
      apt:
        name: gnupg
        state: latest
      when: not gnupg_installed.stat.exists


    - name: Vérifier si Go est déjà installé
        stat:
          path: /usr/bin/go
        register: go_installed


    - name: Installation de GO
      become: true
      apt:
        name: golang
        state: present
        update_cache: yes
        when: not go_installed.stat.exists
#













